### ISSUE TITLE
Incompatible with Firefox

### ISSUE THREAD

**Issue by askvortsov1** [janestreet/ppx_css#1]
As discussed in [this issue](https://github.com/ocsigen/js_of_ocaml/issues/1278), `ppx_css` uses the `CSSStyleSheet()` constructor, which is currently available in Chrome, but not Firefox. This makes dependencies of `ppx_css` (such as Bonsai forms) unusable on Firefox. It looks like Firefox will add this feature [eventually](https://bugzilla.mozilla.org/show_bug.cgi?id=1520690), but in the meantime, if there's no equivalent feature in Firefox, maybe it would be gracefully handle this error on non-Chrome browsers (e.g. raising a debug error to the console, and setting `global_style_sheet` to `None`), so that other libraries aren't broken on Firefox.

**Comment by aalekseyev** [comment]
Something changed related to this issue (closing this, assuming it's fixed).
